# Generated by Django 3.2.11 on 2023-07-18 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_management_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTransactionInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("amount", models.FloatField(default=0.0)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("CREDIT", "Credit"), ("DEBIT", "Debit")], max_length=8
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="aadhar_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_management_service.userinformation",
                    ),
                ),
            ],
        ),
    ]
