# Generated by Django 3.2.11 on 2023-07-18 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_management_service", "0002_usertransactioninformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinformation",
            name="aadhar_id",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="usertransactioninformation",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loan_management_service.userinformation",
                to_field="aadhar_id",
            ),
        ),
    ]
