# Generated by Django 4.2.3 on 2023-07-19 08:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan_management_service", "0003_auto_20230718_0715"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usertransactioninformation",
            old_name="user_id",
            new_name="aadhar_id",
        ),
        migrations.RenameField(
            model_name="usertransactioninformation",
            old_name="date",
            new_name="registration_date",
        ),
        migrations.AddField(
            model_name="userinformation",
            name="credit_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userinformation",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name="LoanInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("loan_type", models.CharField(max_length=64)),
                ("loan_amount", models.IntegerField(default=0)),
                ("annual_interest_rate", models.FloatField()),
                ("term_period", models.IntegerField(default=0)),
                ("disbursement_date", models.DateTimeField()),
                (
                    "user_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_management_service.userinformation",
                        to_field="user_uuid",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EMIDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_due", models.FloatField(default=None)),
                ("amount_paid", models.FloatField(default=0.0)),
                ("installment_date", models.DateTimeField()),
                (
                    "loan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_management_service.loaninfo",
                        to_field="loan_id",
                    ),
                ),
            ],
        ),
    ]
