# Generated by Django 3.2.11 on 2023-07-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_management_service', '0004_rename_user_id_usertransactioninformation_aadhar_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactioninformation',
            name='aadhar_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
